var data = {files:[
{"link":"lazy_frame.ml.eb0a9f7b.html","title":"lazy_frame.ml","summary_name":"[...]/_build/default/lib/lazy_frame.ml","covered_class":"linePartCov","covered":"47.1","covered_lines":"16","uncovered_lines":"18","total_lines" : "34"},
{"link":"lazy_frame.rs.fa611ace.html","title":"lazy_frame.rs","summary_name":"[...]/_build/default/rust/polars-ocaml/src/lazy_frame.rs","covered_class":"linePartCov","covered":"39.6","covered_lines":"108","uncovered_lines":"165","total_lines" : "273"},
{"link":"expr.ml.994fff49.html","title":"expr.ml","summary_name":"[...]/_build/default/lib/expr.ml","covered_class":"linePartCov","covered":"64.7","covered_lines":"33","uncovered_lines":"18","total_lines" : "51"},
{"link":"fill_null_strategy.ml.dc20cb4d.html","title":"fill_null_strategy.ml","summary_name":"[...]/_build/default/lib/fill_null_strategy.ml","covered_class":"lineCov","covered":"100.0","covered_lines":"17","uncovered_lines":"0","total_lines" : "17"},
{"link":"data_type.ml.d6303723.html","title":"data_type.ml","summary_name":"[...]/_build/default/lib/data_type.ml","covered_class":"lineCov","covered":"87.3","covered_lines":"69","uncovered_lines":"10","total_lines" : "79"},
{"link":"schema.ml.4b459a6b.html","title":"schema.ml","summary_name":"[...]/_build/default/lib/schema.ml","covered_class":"lineCov","covered":"100.0","covered_lines":"3","uncovered_lines":"0","total_lines" : "3"},
{"link":"utils.rs.e1c9cb26.html","title":"utils.rs","summary_name":"[...]/_build/default/rust/polars-ocaml/src/utils.rs","covered_class":"lineCov","covered":"81.4","covered_lines":"214","uncovered_lines":"49","total_lines" : "263"},
{"link":"series.ml.f32644c2.html","title":"series.ml","summary_name":"[...]/_build/default/lib/series.ml","covered_class":"lineCov","covered":"78.0","covered_lines":"71","uncovered_lines":"20","total_lines" : "91"},
{"link":"data_frame0.ml.4466aa07.html","title":"data_frame0.ml","summary_name":"[...]/_build/default/lib/data_frame0.ml","covered_class":"lineCov","covered":"100.0","covered_lines":"2","uncovered_lines":"0","total_lines" : "2"},
{"link":"common_intf.ml.f723ccff.html","title":"common_intf.ml","summary_name":"[...]/_build/default/lib/common_intf.ml","covered_class":"lineCov","covered":"100.0","covered_lines":"2","uncovered_lines":"0","total_lines" : "2"},
{"link":"sql_context.ml.23dd3cbd.html","title":"sql_context.ml","summary_name":"[...]/_build/default/lib/sql_context.ml","covered_class":"lineCov","covered":"100.0","covered_lines":"5","uncovered_lines":"0","total_lines" : "5"},
{"link":"sql_context.rs.2b5f983.html","title":"sql_context.rs","summary_name":"[...]/_build/default/rust/polars-ocaml/src/sql_context.rs","covered_class":"linePartCov","covered":"73.7","covered_lines":"28","uncovered_lines":"10","total_lines" : "38"},
{"link":"timezones.rs.42cb5b50.html","title":"timezones.rs","summary_name":"[...]/_build/default/rust/target/debug/build/chrono-tz-0aa73b6cd7cecec5/out/timezones.rs","covered_class":"lineNoCov","covered":"0.7","covered_lines":"16","uncovered_lines":"2383","total_lines" : "2399"},
{"link":"data_frame.rs.c66d23b9.html","title":"data_frame.rs","summary_name":"[...]/_build/default/rust/polars-ocaml/src/data_frame.rs","covered_class":"lineCov","covered":"84.1","covered_lines":"292","uncovered_lines":"55","total_lines" : "347"},
{"link":"misc.rs.541e8daa.html","title":"misc.rs","summary_name":"[...]/_build/default/rust/polars-ocaml/src/misc.rs","covered_class":"lineCov","covered":"93.8","covered_lines":"60","uncovered_lines":"4","total_lines" : "64"},
{"link":"series.rs.9587c14d.html","title":"series.rs","summary_name":"[...]/_build/default/rust/polars-ocaml/src/series.rs","covered_class":"lineCov","covered":"80.9","covered_lines":"318","uncovered_lines":"75","total_lines" : "393"},
{"link":"expr.rs.7e58d9.html","title":"expr.rs","summary_name":"[...]/_build/default/rust/polars-ocaml/src/expr.rs","covered_class":"linePartCov","covered":"64.5","covered_lines":"378","uncovered_lines":"208","total_lines" : "586"},
{"link":"polars_async.ml.22044180.html","title":"polars_async.ml","summary_name":"[...]/_build/default/async/polars_async.ml","covered_class":"lineCov","covered":"100.0","covered_lines":"1","uncovered_lines":"0","total_lines" : "1"},
{"link":"polars.ml.52194aa3.html","title":"polars.ml","summary_name":"[...]/_build/default/lib/polars.ml","covered_class":"lineCov","covered":"100.0","covered_lines":"2","uncovered_lines":"0","total_lines" : "2"},
{"link":"common.ml.2ce223a9.html","title":"common.ml","summary_name":"[...]/_build/default/lib/common.ml","covered_class":"lineCov","covered":"89.6","covered_lines":"43","uncovered_lines":"5","total_lines" : "48"},
{"link":"env.ml.4afa4533.html","title":"env.ml","summary_name":"[...]/_build/default/lib/env.ml","covered_class":"lineCov","covered":"100.0","covered_lines":"27","uncovered_lines":"0","total_lines" : "27"},
{"link":"join_type.ml.609e0ab2.html","title":"join_type.ml","summary_name":"[...]/_build/default/lib/join_type.ml","covered_class":"lineNoCov","covered":"23.1","covered_lines":"3","uncovered_lines":"10","total_lines" : "13"},
{"link":"lib.rs.f5022ca1.html","title":"lib.rs","summary_name":"[...]/_build/default/rust/polars-ocaml/src/lib.rs","covered_class":"lineCov","covered":"100.0","covered_lines":"1","uncovered_lines":"0","total_lines" : "1"},
{"link":"utils.ml.8b2d807d.html","title":"utils.ml","summary_name":"[...]/_build/default/lib/utils.ml","covered_class":"lineCov","covered":"100.0","covered_lines":"3","uncovered_lines":"0","total_lines" : "3"},
{"link":"lazy_frame.ml.6b82e73d.html","title":"lazy_frame.ml","summary_name":"[...]/_build/default/async/lazy_frame.ml","covered_class":"linePartCov","covered":"50.0","covered_lines":"5","uncovered_lines":"5","total_lines" : "10"},
{"link":"data_frame.ml.d706a60c.html","title":"data_frame.ml","summary_name":"[...]/_build/default/lib/data_frame.ml","covered_class":"linePartCov","covered":"69.6","covered_lines":"55","uncovered_lines":"24","total_lines" : "79"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2023-09-23 10:46:05", "instrumented" : 4831, "covered" : 1772,};
var merged_data = [];
